// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6aSSbFzeWsu8LQWnZvh5ZjtdMzY-OzQY',
    appId: '1:94629892010:web:52909be6a39a2de1bd65d3',
    messagingSenderId: '94629892010',
    projectId: 'todoapp-24cca',
    authDomain: 'todoapp-24cca.firebaseapp.com',
    storageBucket: 'todoapp-24cca.appspot.com',
    measurementId: 'G-CXWM5KYEJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOxyN_ef1SJf9NbhkXUh3hkGtegvr3xVU',
    appId: '1:94629892010:android:0204fd8f13332981bd65d3',
    messagingSenderId: '94629892010',
    projectId: 'todoapp-24cca',
    storageBucket: 'todoapp-24cca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2HJVeiL6sqkIr9XtyBc85DcZoJK9BOB4',
    appId: '1:94629892010:ios:06a1b1dcb27ba3d7bd65d3',
    messagingSenderId: '94629892010',
    projectId: 'todoapp-24cca',
    storageBucket: 'todoapp-24cca.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2HJVeiL6sqkIr9XtyBc85DcZoJK9BOB4',
    appId: '1:94629892010:ios:ca2dc63b4a6b1bb4bd65d3',
    messagingSenderId: '94629892010',
    projectId: 'todoapp-24cca',
    storageBucket: 'todoapp-24cca.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
